name: github_graphql_client
description: Github client using Github API V4 (GraphQL)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fluttericon: ^1.0.7        # Add this dependency.
  gql: ^0.12.3
  gql_exec: ^0.2.4
  gql_link: ^0.3.0
  gql_http_link: ^0.3.2
  gql_transform_link: ^0.1.5
  http: ^0.12.1
  oauth2: ^1.6.1
  url_launcher: ^5.4.10
  window_to_front:
    path: '../window_to_front'

dev_dependencies:
  build_runner: ^1.10.11
  gql_build: ^0.0.11
  pedantic: ^1.9.0

flutter:
  uses-material-design: true